
# source1: php, apache, folder, access, port - https://medium.com/@chandrajeetmaurya/docker-compose-setting-up-web-development-stack-step-by-step-81e557a69863
# source2: mysql - https://medium.com/@chandrajeetmaurya/docker-compose-setting-up-web-development-stack-step-by-step-part-2-mysql-298b13c6483e
# source3: mariadb - https://hub.docker.com/_/mariadb
# source4: https://medium.com/@chandrajeetmaurya/docker-compose-setting-up-web-development-stack-step-by-step-part-3-phpmyadmin-23c6d67768b7


version: "3.7"
services:
    practice_server_service_1: #service name
      container_name: practice_server_service_1
      build: #image we want to use
          context: .
          dockerfile: /docker/web/Dockerfile
      ports:
        - 80:80 #<-- to visit this site once up and running 127.0.0.1:8090 but it says  (You don’t have permission to access this resource. Apache/2.4.38 (Debian) Server at 127.0.0.1 Port 8090) but atleast we can now access with port
#      tty: true
#      working_dir: /var/www/html/public
      volumes:
      # ./www/app <--- this is pointed to my root folder in my local environment
      # /var/www/html <--- this is pointed to server
      # /var/www/html is in apache and my folder ./www/app folder is pointed to apache /var/www/html (so it's overriding the apache content
        - ./var/www/html:/var/www/html
        - ./docker/web/apache2/apache2.conf:/etc/apache2/apache2.conf
        - ./docker/web/docker-entrypoint.sh:/docker-entrypoint.sh
        - ./docker/web/apache2/sites-enabled:/etc/apache2/sites-enabled/
        - ./docker/web/apache2/sites-enabled:/etc/apache2/sites-available/
      # - ./docker/etc/apache2/php.ini:/usr/local/etc/php/php.ini
      depends_on:
        - "db"
      networks:
        - default
      #links:
      #  - mysql:database
    db: #<--- after adding new container and services you must run docker-compose up -d to recreated (I used mariadb because mysql is having issue in my version I don't know why is that happening.) The issue was about  -- too many symbolic links
        #<--- I can connect to the server through in phpstorm,syslogs - host:localhost, user:root, pass:root, port3306, database:mydatabase
        #<--- I can connect with laravel .env throught this information host:db, user:root, pass:root, port:3306, database:mydatabase
        # -  in the .env host must be inline to db docker service name

        container_name: practice_database_1
        restart: unless-stopped
        tty: true
        ports:
           - 3306:3306
        image: mariadb
        restart: always
        environment:
             MYSQL_ROOT_PASSWORD: root
             MYSQL_USER: myusername
             MYSQL_PASSWORD: mypassword
             MYSQL_DATABASE: mydatabase
#         volumes:
#            - wp-mysql-data:/var/lib/mysql
        networks:
          - default


    # This is part of maridb installation -> not sure how it works at the moment
    #  adminer:
    # image: adminer
    # restart: always
    # ports:
    #  - 8081:80


    pma:
        container_name: practice_phpmyadmin_1
        image: phpmyadmin/phpmyadmin
        ports:
          - 8080:80 #<-- without link below, we can access the phpmyadmin host:port -> http://127.0.0.1:8080/ but can't login, and if added with link then we can now login to root/root. Just make sure to run docker-compose up -d when you have changes to your docker-compose.yml.yml file
        links:
              - mysql:db #<---  links: <service-name>:<alias-name> this will allow us to login in phpmyadmin with the username and password for root/root

#networks:
#  default:
#    driver: bridge

